import hashlib
import hmac
import logging

from sqlalchemy import select

from app.config import get_settings
from app.db import SessionLocal
from app.models import RawEvent
from app.normalizer import normalize_event

logger = logging.getLogger(__name__)

RECOVERY_EVENTS = {
    "payment.failed",
    "payment.captured",
    "subscription.pending",
    "subscription.charged",
    "subscription.halted",
    "invoice.paid",
    "payment_link.paid",
}


def verify_signature(body: bytes, signature: str, secret: str) -> bool:
    expected = hmac.new(secret.encode(), body, hashlib.sha256).hexdigest()
    return hmac.compare_digest(expected, signature)


def ingest_event(event: dict, raw_body: bytes, signature: str, event_id: str) -> dict:
    """Single entry point for every recovery-relevant event, whether it arrives
    over HTTP or is generated by the world simulator. Verifies the HMAC
    signature over the exact bytes the sender produced, dedups on event id,
    stores the raw event, and normalizes it into case state. Returns an
    ingest status dict."""
    if not verify_signature(raw_body, signature, get_settings().rzp_webhook_secret):
        return {"status": "invalid_signature"}

    event_type = event.get("event", "")
    with SessionLocal() as db:
        existing = db.scalar(select(RawEvent).where(RawEvent.event_id == event_id))
        if existing is not None:
            return {"status": "duplicate_ignored", "event_id": event_id}

        raw = RawEvent(event_id=event_id, event_type=event_type, payload=event)
        db.add(raw)
        db.commit()

    if event_type in RECOVERY_EVENTS:
        safe_normalize(event_id)

    return {"status": "accepted", "event_id": event_id, "event_type": event_type}


def safe_normalize(event_id: str) -> None:
    try:
        with SessionLocal() as db:
            raw = db.scalar(select(RawEvent).where(RawEvent.event_id == event_id))
            if raw is None or raw.processed:
                return
            case_id = normalize_event(db, raw)
            raw.processed = True
            db.commit()
            logger.info("event %s -> case %s", event_id, case_id)
    except Exception:
        logger.exception("failed to process event %s", event_id)
